version: "3.9"
services:
  back:
    container_name: backcontainer
    build:
        context: ./backend/
        dockerfile: ./Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - '//var/run/docker.sock:/var/run/docker.sock'
  front:
    build:
        context: ./frontend/
        dockerfile: ./Dockerfile
    ports:
      - "3000:3000"